"""Shared PDF styling for the project's public documents.

These documents previously had no source in the repository: the Russian
abstract was compiled with pdfTeX and the talk outline was printed from a
browser, and neither source survived. Everything published from here on is
generated by these scripts so it can be regenerated and re-translated.
"""
import os
import subprocess
import tempfile

from fpdf import FPDF

FONT_CANDIDATES = [
    "/Library/Fonts/Arial Unicode.ttf",
    "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
]

BLACK = (17, 17, 17)
BLUE = (0, 70, 180)
GRAY = (110, 110, 110)
RULE = (210, 210, 210)

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PUBLIC = os.path.join(BASE, "public")


def _font_path():
    for p in FONT_CANDIDATES:
        if os.path.exists(p):
            return p
    raise SystemExit(
        "No Unicode font found. Install one of:\n  " + "\n  ".join(FONT_CANDIDATES)
    )


class DocPDF(FPDF):
    """A4 document with a running header and simple typographic helpers."""

    def __init__(self, running_title):
        super().__init__(format="A4")
        self._running = running_title
        font = _font_path()
        self.add_font("doc", "", font)
        self.add_font("doc", "B", font)
        self.set_auto_page_break(auto=True, margin=20)
        self.set_margins(22, 18, 22)

    # --- page furniture ---------------------------------------------------
    def header(self):
        if self.page_no() == 1:
            return
        self.set_font("doc", "", 7.5)
        self.set_text_color(*GRAY)
        self.cell(0, 4, self._running, align="L")
        self.cell(0, 4, str(self.page_no()), align="R", new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(*RULE)
        self.line(self.l_margin, self.get_y() + 1, self.w - self.r_margin, self.get_y() + 1)
        self.ln(5)

    def footer(self):
        if self.page_no() == 1:
            return
        self.set_y(-14)
        self.set_font("doc", "", 7)
        self.set_text_color(*GRAY)
        self.cell(0, 4, "rocketlauncher.space", align="C")

    # --- text helpers -----------------------------------------------------
    def title_block(self, title, subtitle, author):
        self.ln(14)
        self.set_font("doc", "B", 17)
        self.set_text_color(*BLACK)
        self.multi_cell(0, 8.5, title, align="C")
        self.ln(3)
        self.set_font("doc", "", 11)
        self.set_text_color(*GRAY)
        self.multi_cell(0, 6, subtitle, align="C")
        self.ln(6)
        self.set_font("doc", "", 10.5)
        self.set_text_color(*BLACK)
        self.cell(0, 6, author, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(8)
        self.set_draw_color(*RULE)
        self.line(self.w / 2 - 25, self.get_y(), self.w / 2 + 25, self.get_y())
        self.ln(8)

    def h1(self, text):
        if self.get_y() > self.h - 55:
            self.add_page()
        self.ln(3)
        self.set_font("doc", "B", 13)
        self.set_text_color(*BLUE)
        self.multi_cell(0, 7, text)
        self.ln(1.5)

    def h2(self, text):
        self.ln(1)
        self.set_font("doc", "B", 10.5)
        self.set_text_color(*BLACK)
        self.multi_cell(0, 6, text)
        self.ln(0.5)

    def para(self, text):
        self.set_font("doc", "", 10.5)
        self.set_text_color(*BLACK)
        self.multi_cell(0, 5.6, text, align="J")
        self.ln(2)

    def bullets(self, items, numbered=False):
        self.set_font("doc", "", 10.5)
        self.set_text_color(*BLACK)
        for i, item in enumerate(items, 1):
            marker = f"{i}." if numbered else "•"
            x = self.get_x()
            self.cell(7, 5.6, marker)
            self.multi_cell(0, 5.6, item)
            self.set_x(x)
            self.ln(0.6)
        self.ln(2)

    # Millimetres per rendered pixel. Constant across every equation so that
    # they all typeset at the same size regardless of how wide they are.
    EQ_SCALE = 0.078

    def equation(self, mathtext):
        """Typeset a LaTeX-style expression via matplotlib (no TeX install)."""
        png = _render_math(mathtext)
        px_w, px_h = _png_size(png)
        w = px_w * self.EQ_SCALE
        if w > self.epw:                      # very wide expression: fit the page
            w = self.epw
        h = px_h * (w / px_w)
        x = (self.w - w) / 2
        self.image(png, x=x, w=w, h=h)
        self.ln(3)


def _png_size(path):
    """Read width/height straight from the PNG IHDR chunk (no extra deps)."""
    with open(path, "rb") as fh:
        head = fh.read(24)
    return int.from_bytes(head[16:20], "big"), int.from_bytes(head[20:24], "big")


def _render_math(expr, dpi=440):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    fig = plt.figure(figsize=(0.01, 0.01))
    fig.text(0, 0, expr, fontsize=13, color="#111111")
    tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    fig.savefig(tmp.name, dpi=dpi, transparent=False, facecolor="white",
                bbox_inches="tight", pad_inches=0.04)
    plt.close(fig)
    return tmp.name
